import Head from "next/head";
import { type NextPage } from "next";
import Chart from "./components/Chart";
import { useProtectedPage } from "./hooks/useProtectedPage";

const Home: NextPage = () => {
  useProtectedPage();
  return (
    <>
      <Head>
        <title>IPC app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Chart />
    </>
  );
};

export default Home;
