import Head from "next/head";
import { type FC, useRef, useState, useEffect } from "react";
import { ChartId, ClassNames } from "./Chart.constants";
import { useChart } from "./Chart.hooks";

const Chart: FC = () => {
  const cardRef = useRef<HTMLDivElement>(null);
  const [cardDimensions, setCardDimensions] = useState({ width: 0, height: 0 });
  useChart({ ...cardDimensions });

  const handleSetCardDimensions = (): void => {
    if (cardRef.current) {
      const { offsetWidth: width } = cardRef.current;
      setCardDimensions({
        width,
        height: width / 2,
      });
    }
  };

  useEffect(() => {
    if (cardRef.current) {
      handleSetCardDimensions();
    }
  }, []);

  return (
    <>
      <Head>
        <title>IPC app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto py-10">
        <div ref={cardRef} className="rounded-lg bg-neutral-100 shadow">
          <svg
            width={cardDimensions.width}
            height={cardDimensions.height}
            viewBox={`0 0 ${cardDimensions.width} ${cardDimensions.height}`}
          >
            {/* <rect
              id={ChartId.Tooltip}
              style={{ pointerEvents: "none" }}
              width="20px"
              height="10px"
            /> */}
            <g id={ChartId.XAxis} />
            <g id={ChartId.YAxis}>
              <text
                textAnchor="end"
                fill="currentColor"
                id={ChartId.YAxisLabel}
                className={ClassNames.Text}
              >
                Price
              </text>
            </g>
            <path
              id={ChartId.Line}
              strokeWidth={1.5}
              strokeLinecap="round"
              strokeLinejoin="round"
              className="fill-none stroke-gray-700"
            />
          </svg>
        </div>
      </div>
    </>
  );
};

export default Chart;
